fix: fixed semver-compare test

diff --git a/.github/workflows/_internal-semver-compare.yaml b/.github/workflows/_internal-semver-compare.yaml
--- a/.github/workflows/_internal-semver-compare.yaml
+++ b/.github/workflows/_internal-semver-compare.yaml
@@ -38,8 +38,8 @@ jobs:
       - uses: ./semver-compare
         id: version-compare-3
         with:
-          version: 2.2
-          compare_against: 2.2.1
+          version: 2.2.1
+          compare_against: 2.2
 
 
       - uses: ./semver-compare
@@ -49,13 +49,13 @@ jobs:
           compare_against: 2.2.0
 
       - name: Fail if 2.3 is not higher than 2.2.3
-        if: steps.version-compare-1.outputs.version != 1
+        if: steps.version-compare-1.outputs.version != -1
         shell: bash
-        run: echo "FAIL because 2.3 must be higher than 2.2.3 Compare 2.3 to 2.2.3 renders ${{ steps.version-compare-1.outputs.result }}" && exit 1
+        run: echo "FAIL because 2.3 must be higher than 2.2.3 Compare 2.2.3 to 2.3 renders ${{ steps.version-compare-1.outputs.result }}" && exit 1
 
 
       - name: Fail if 2.0.1 is not higher than 2
-        if: steps.version-compare-2.outputs.version != 1
+        if: steps.version-compare-2.outputs.version != -1
         shell: bash
         run: echo "FAIL because 2.0.1 must be higher than 2 Compare 2 to 2.0.1 renders ${{ steps.version-compare-2.outputs.result }}" && exit 1
 
