fix: fixed semver-compare test

diff --git a/.github/workflows/_internal-semver-compare.yaml b/.github/workflows/_internal-semver-compare.yaml
--- a/.github/workflows/_internal-semver-compare.yaml
+++ b/.github/workflows/_internal-semver-compare.yaml
@@ -65,6 +65,6 @@ jobs:
         run: echo "FAIL because 2.2.1 must be higher than 2.2 Compare 2.2.1 to 2.2 renders ${{ steps.version-compare-3.outputs.result }}" && exit 1
 
       - name: Fail if 2.2.0 is not equals to 2.2.0
-        if: steps.version-compare-4.outputs.result != 0
+        if: steps.version-compare-4.outputs.result != '0'
         shell: bash
-        run: echo "FAIL because 2.2.0 must be equals to 2.2.0 Compare 2.2.0 to 2.2.0 renders ${{ steps.version-compare-4.outputs.result }}" && exit 1
+        run: echo "FAIL because 2.2.0 must be equal to 2.2.0 Compare 2.2.0 to 2.2.0 renders ${{ steps.version-compare-4.outputs.result }}" && exit 1
